# Generated by Django 6.0.2 on 2026-02-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_barcodehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplan',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='dietplan',
            old_name='description',
            new_name='plan_content',
        ),
        migrations.RemoveField(
            model_name='barcodehistory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='barcodehistory',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='barcodehistory',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='barcodehistory',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='barcodehistory',
            name='nutri_score',
        ),
        migrations.RemoveField(
            model_name='barcodehistory',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='diet_preference',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='health_condition',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='scannedproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='scannedproduct',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='scannedproduct',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='scannedproduct',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='scannedproduct',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='scannedproduct',
            name='nutri_score',
        ),
        migrations.RemoveField(
            model_name='scannedproduct',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='scannedproduct',
            name='sugar',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='health_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scannedproduct',
            name='nutritional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barcodehistory',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barcodehistory',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scannedproduct',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scannedproduct',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
